config/routes.rb
Rails.application.routes.draw do

  root 'activities#index'

  resources :activities

  resources :replies, only: [:create]
  
  resources :tickets do
    member do
      get 'versions' => 'tickets#versions'
    end
    resources :replies, only: [:index, :create]
  end

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  devise_for :users

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

  include PublicActivity::Model
  include UniqueToken
  has_paper_trail
  tracked owner: Proc.new{ |controller, model| 
    controller.current_user ? controller.current_user : model
  }

  belongs_to :status
  belongs_to :assignee, class_name: "User"
  belongs_to :department
  has_many :replies

  validates :department, :status, :subject, :body, :consumer_name, :consumer_email,
    presence: true

  validates :consumer_email, 
    email: true

  before_validation :set_status, on: :create
  after_create :email_consumer


  scope :assigned_to_user_with_id, -> (user_id) { where assignee_id: user_id }
  scope :unassigned, -> { where assignee_id: nil }
  scope :with_token, -> (token) { where(unique_token: token).first! }
  

  def get_versions_with_consumer_changes
    versions = []
    self.versions.each do |v|
      unless v.reify.nil? or v.changeset.nil?
        unless (v.changeset.keys & ['subject', 'body']).empty?
          versions << v.reify
        end
      end   
    end
    versions
  end

  def self.ransackable_scopes(auth_object = nil)
    [:unassigned, :assigned_to_user_with_id]
  end


  private


  def email_consumer
    ConsumerMailer.ticket_reference_email(self).deliver_now
  end

  def set_status
    self.status = Status.initial
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  include RememberableCheckboxes
  include AllowCors

  inherit_resources

  skip_before_filter :verify_authenticity_token, :only => [:create]
  before_filter :authenticate_user!, except: [:create, :show, :edit, :update]



  def index
    @q = Ticket.ransack(params[:q])
    @tickets = @q.result.page(params[:page]).to_a.uniq

    init_selected 'department_names'
    init_selected 'status_names'
    init_selected 'assignee_ids', methods: ['eq', 'null']
  end

  def show
    if current_user
      @ticket = Ticket.where(id: params[:id]).includes(replies: :author).first!
      @reply = Reply.new(author_id: current_user.id, ticket_id: @ticket.id)
    else
      @ticket = Ticket.with_token(params[:id])
    end
  end

  def new
    new! layout: 'embeded_ticket_form'
  end

  def edit
    if current_user
      redirect_to ticket_path(params[:id])
    else
      @ticket = Ticket.with_token(params[:id])
    end
  end

  def update
    if current_user
      update!
    else
      @ticket = Ticket.with_token(params[:id])
      @ticket.update_attributes(ticket_params)
      @ticket.save()
      if @ticket.errors.any?
        render :edit
      else
        render :show, id: params[:id], flash:{notice: 'Updated'}
      end
    end
  end

  def create
    t = Ticket.new(ticket_params)
    if t.save()
      render json: 'thank you!'
    else
      render json: t.errors
    end
  end


  def versions
    ticket = Ticket.find(params[:id])
    @versions = ticket.get_versions_with_consumer_changes
  end


  private

  @@public_params_for_update = [
    :subject, 
    :body, 
    :consumer_name,
    :updated_by_consumer_at
  ]

  @@public_params_for_create = [
    :department_id, 
    :subject, 
    :body, 
    :consumer_name, 
    :consumer_email,
    :updated_by_consumer_at
  ]

  @@staff_permitted = @@public_params_for_create & @@public_params_for_update.push(:assignee_id, :status_id, :updated_by_staff_at)

  def ticket_params
    if current_user
        params.require(:ticket).permit(*@@staff_permitted).merge({updated_by_staff_at: DateTime.now})
    else
      if action_name == 'update'
        par = @@public_params_for_update
      elsif action_name == 'create'
        par = @@public_params_for_create
      end
      params.require(:ticket).permit(*par).merge({updated_by_consumer_at: DateTime.now})
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def departments
    Department.all
  end

  def statuses
    Status.all
  end

  def search_input(tag_name, name, operator, value, selected, id: nil)
    arr = operator == 'cont_any' ? '[]' : '' 
    send( 
      tag_name, 
      "q[#{name}_#{operator}]#{arr}", 
      value, 
      !selected[operator].nil? && selected[operator].include?(value), 
      id: id.nil? ? "#{name}_#{operator}_#{value}" : id, 
      class: 'search_checkbox')
  end

end

app/views/tickets/_form.html.slim
= form_for(@ticket, as: :ticket, url: @ticket.id.nil? ? tickets_path  : ticket_path(@ticket.unique_token)) do |f|
  - if @ticket.errors.any?
    #error_explanation
      h2 = "#{pluralize(@ticket.errors.count, "error")} prohibited this ticket from being saved:"
      ul
        - @ticket.errors.full_messages.each do |message|
          li = message
  - unless @ticket.id
    .field-grop
      = f.label :department_id
      = f.collection_select :department_id, departments, :id, :name, {prompt: true}, {class: 'form-control'}
  .field-grop
    = f.label :subject
    = f.text_field :subject, class: 'form-control'
  .field-grop
    = f.label :body
    = f.text_area :body, class: 'form-control'
  .field-grop
    = f.label 'Your name'
    = f.text_field :consumer_name, class: 'form-control'
  - unless @ticket.id
    .field-grop
      = f.label 'Your email'
      = f.text_field :consumer_email, class: 'form-control'
  .actions = f.submit "Send", class: 'btn btn-primary'

app/views/tickets/_reply_form.html.slim
= form_for @reply do |f|
  - if @reply.errors.any?
    #error_explanation
      h2 = "#{pluralize(@reply.errors.count, "error")} prohibited this reply from being saved:"
      ul
        - @reply.errors.full_messages.each do |message|
          li = message
  .form-group
    = f.label :reply
    = f.text_area :reply_body, class: 'form-control', required: true
  = f.hidden_field :author_id
  = f.hidden_field :ticket_id
  .actions
    = f.submit "Reply", class: 'btn btn-primary'

app/views/tickets/_short_form.html.slim
= form_for @ticket do |f|
  - if @ticket.errors.any?
    #error_explanation
      h2 = "#{pluralize(@ticket.errors.count, "error")} prohibited this ticket from being saved:"
      ul
        - @ticket.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :department_id
    = f.collection_select :department_id, departments, :id, :name, {prompt: true}, {class: 'form-control'}
  .form-group
    = f.label :status_id
    = f.collection_select :status_id,     statuses,    :id, :name, {prompt: true}, {class: 'form-control'}
  - if current_user
    .field
      = f.label :assignee_id
      = f.collection_select :assignee_id, User.all.decorate, :id, :name, {prompt: 'unassigned'}, {class: 'form-control'}
  .actions = f.submit class: 'btn btn-warning'

app/views/tickets/_side_info.html.slim
.panel.panel-default
  .panel-heading
    | Department
  .panel-body
    = @ticket.department.name
.panel.panel-default
  .panel-heading
    | Status
  .panel-body
    = @ticket.status.name

app/views/tickets/edit.html.slim
h1 Editing ticket

== render 'form'

= link_to 'Show', @ticket
'|
= link_to 'Back', tickets_path

app/views/tickets/index.html.slim
#wrapper
  /! Sidebar
  #sidebar-wrapper
    = search_form_for @q, id: "search_form" do |f|
      ul.sidebar-nav
        li.section Search
        li.nohover.search
          .form-group
            = f.search_field :subject_or_body_or_unique_token_cont, placeholder: "Search in Subject/Body", autofocus: true, onfocus: 'this.value = this.value', class: 'form-control', 'data-tip' => 'lolol'
        li.section
          | Owner    
          li
            = search_input 'check_box_tag', 'assignee_id', 'eq', current_user.id.to_s, @selected_assignee_ids, id: 'current_user_filter'
            = "Assigned to me"
          li
            = search_input 'check_box_tag', 'assignee_id', 'null', '1', @selected_assignee_ids,  id: 'no_assignee_filter'
            = "Unassigned"

        li.section
          | Departments
        - departments.each do |dep|      
          li
            = search_input 'check_box_tag', 'department_name', 'cont_any', dep.name, @selected_department_names
            = dep.name

        li.section
          | Statuses
        - statuses.each do |st|
          li
            = search_input 'check_box_tag', 'status_name', 'cont_any', st.name, @selected_status_names
            = st.name
        li.section
          = f.submit "Filter", class: 'btn btn-default'


  #page-content-wrapper
    .row
      .col-md-12
        h1 Listing tickets
    .row
      .col-md-12
        table.table
          thead
            tr
              th = sort_link(@q, :department_name, 'Department', default_order: :desc)
              th = sort_link(@q, :status, 'Status', default_order: :desc)
              th = sort_link(@q, :subject, 'Subject', default_order: :desc)
              th = sort_link(@q, :assignee_last_name, 'Assignee', default_order: :asc)
              th = sort_link(@q, :updated_at, 'Last update', default_order: :desc)
              th
              th
              th

          tbody
            - @tickets.each do |ticket|
              tr
                td = ticket.department.name
                td = ticket.status.name
                td = ticket.subject
                td = ticket.assignee ? ticket.assignee.username : "-"
                td = ticket.updated_at.to_formatted_s(:short)
                td = link_to 'Show', ticket
        br

        / = link_to 'New Ticket', new_ticket_path

app/views/tickets/new.html.slim
== render 'form'

app/views/tickets/show.html.slim
.row
  .col-md-12
    h4 
      | Ticket ##{current_user ? @ticket.id : @ticket.unique_token}, created: #{@ticket.created_at.to_formatted_s(:short)}
    - if @ticket.updated_by_consumer_at.to_i != @ticket.created_at.to_i && current_user
      button.btn.btn-danger.btn-xs#diffbutton
        | costumer update #{@ticket.updated_by_consumer_at.to_formatted_s(:short)} (click to show all versions)
  .col-md-8
    #tickets_container
      .panel.panel-info#ticket
        .panel-heading 
          strong.ticket_subject
            = @ticket.subject
        .panel-body.ticket_body
          = @ticket.body

        .panel-footer.consumer-info
          strong Sent by: 
          span.consumer_name
            = @ticket.consumer_name 
            |  &nbsp;&nbsp;
          i.fa.fa-envelope
          span.consumer_email
            = @ticket.consumer_email
            |  &nbsp;&nbsp;
          i.fa.fa-calendar
          span.ticket_created_at
            = @ticket.updated_by_consumer_at.to_formatted_s(:short)


    - unless current_user
      = link_to "Edit ticket", edit_ticket_path(@ticket.unique_token), {class: 'btn btn-warning'}

    - if @ticket.replies.any?
      h4 Replies
      - @ticket.replies.each do |r|
        .panel.panel-success
          .panel-heading
            i.fa.fa-time
            = r.created_at.to_formatted_s(:short)
            |  &nbsp;&nbsp;
            - if current_user
              i.fa.fa-user
              = r.author.username 
          .panel-body
            = r.reply_body
    - if current_user
      == render 'reply_form'

  .col-md-4
    - if current_user
      == render 'short_form'
      strong Last staff upd:
      span.updated_at
        - if @ticket.updated_by_staff_at
          = @ticket.updated_by_staff_at.to_formatted_s(:short)
        - else
          | Ticket were not updated by staff
    - else
      == render 'side_info'



- if current_user
  = link_to 'Back', tickets_path