config/routes.rb
Rails.application.routes.draw do

  root 'activities#index'

  resources :activities

  resources :replies, only: [:create]
  
  resources :tickets do
    member do
      get 'versions' => 'tickets#versions'
    end
    resources :replies, only: [:index, :create]
  end

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  devise_for :users

end

app/views/layouts/_activities.html.slim
.activity
  .panel.panel-default
    .mega-icon style="background-image: url(#{image_path "icons/#{a.key}.svg"})"
    =' timeago a.created_at
    .title
      - if a.owner
        =' link_to a.owner.nickname, a.owner
      - else
        ' someone
      =' content_for :action
    .details
      .avatar
        - if a.owner
          = image_tag a.owner.avatar_url, width: "30", height: "30"
        - else
          = image_tag "http://i0.wp.com/a248.e.akamai.net/assets.github.com/images/gravatars/gravatar-140.png", width: "30", height: "30"
      = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title = ENV['company_name']
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    = nav_bar fixed: :top, brand: ENV['company_name']
      - if current_user
        = menu_group
          = menu_item "Activities", activities_path
          = menu_item "Tickets", tickets_path
        = menu_group pull: :right do
          = menu_item  "Log Out (#{current_user.username})", destroy_user_session_path, method: :delete

    == bootstrap_flash

    .container
      = yield

app/views/layouts/embeded_ticket_form.html.slim
doctype html
html
  head
    title = ENV['company_name']
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body style="padding: 0 !important;"
    == bootstrap_flash

    .container-fluid
      = yield